### ISSUE TITLE
Add lat/long to `locations`

### ISSUE THREAD

**Issue by jamiew** [helium/blockchain-etl#106]
We store city, state, etc. as geocoded from Google Maps, but not a raw long/lat. `blockchain-http` adds these to API results dynamically, but it would be very useful for data analysts to have a lat/long attached to each h3 location. 

This would allow for utilizing postgis geo-spatial queries, like "hotspots within given area" or "nearby hotspots." It would also enable building visualizations directly in data analysis tools like Metabase, which is used for https://etl.dewi.org

**Comment by madninja** [comment]
Would this be fixed by: https://github.com/helium/blockchain-etl/pull/137 and using the appropriate parameters?

**Comment by jamiew** [comment]
Yep this is done and done
