### ISSUE TITLE
More than 48 hours， database no start populating 

### ISSUE THREAD

**Issue by Yangxin-GG** [helium/blockchain-etl#117]
![image](https://user-images.githubusercontent.com/30194654/104403868-6e5c5e00-5594-11eb-91be-00bf6e722d25.png)
It's always the same data. It hasn't changed

**Comment by Yangxin-GG** [comment]
Only the data of the first block
etl log：
![image](https://user-images.githubusercontent.com/30194654/104403956-a499dd80-5594-11eb-987f-536ef84a2b7a.png)
It seems that it has been synchronized to a high level, but there is still no data in the database

**Comment by abhay** [comment]
You will see that line until you reach the [blessed snapshot height](https://github.com/helium/blockchain-etl/blob/master/config/sys.config#L63).

**Comment by Yangxin-GG** [comment]
Okay, I'll wait

Regarding sending transactions, can you tell me how to structure transactions? The document (Submit a New Transaction) does not seem to be clearly stated

**Comment by Yangxin-GG** [comment]
I found (helium/proto), but after building it with RUST, I don’t know how to use this JS

**Comment by Yangxin-GG** [comment]
thank you

**Comment by jamiew** [comment]
@Yangxin-GG to add on – the ETL first syncronizes the ledger, then starts transcribing blocks into postgres. It can take a week or more depending on your hardware

**Comment by madninja** [comment]
@Yangxin-GG f you need a local blockchain node to talk to with a simple
