### ISSUE TITLE
Build Error psql Migration failed 

### ISSUE THREAD

**Issue by nmharmon8** [helium/blockchain-etl#153]
Hi, 

I am working on running my own node. I am getting an error when I run "make release".

```
 make release
./rebar3 as dev do release
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Plugin rebar3_eqc does not export init/1. It will not be used.
===> Compiling psql_migration
===> Compiling _build/default/lib/psql_migration/src/psql_migration.erl failed
_build/default/lib/psql_migration/src/psql_migration.erl:176: http_uri:parse/2 is deprecated and will be removed in OTP 25; use use uri_string functions instead

make: *** [Makefile:42: release] Error 1
```

The .env:
```
DATABASE_URL=postgresql://postgres:<mypassword>@a0073de5f7ae
```

I can connect fine with psql: 
```
psql -h a0073de5f7ae -U postgres
```
I pulled tag: 1.1.84

Thanks

**Comment by jamiew** [comment]
What is the version number you see when you run "erl"? I suspect you are using a newer version of Erlang OTP than what is specified in the README

**Comment by nmharmon8** [comment]
Yeah your are correct. I don't know how I put the wrong version into my docker file :( . Thanks for the help.

**Comment by jamiew** [comment]
There is another PR open with a Dockerfile you should check out--
@jamiew <https://twitter.com/jamiew> | https://jamiedubs.com
<https://www.jamiedubs.com/>

**Comment by nmharmon8** [comment]
Thanks. I will take a look.
