### ISSUE TITLE
Different responses from https://api.helium.io/v1 

### ISSUE THREAD

**Issue by APshenkin** [helium/blockchain-etl#162]
We faced with issue that api.helium.io return different responses when we call it from different places. When we call

```
curl --location --request GET 'https://api.helium.io/v1/accounts/132eiufNkm7DedxkVYnzEwFgj96McokvV7RYgzKVgxhdrbvNpKA/activity' \
--header 'Content-Type: application/json'
```

locally, the response is 
```
{
    "data": [],
    "cursor": "eyJtaW5fYmxvY2siOjgwNzU2MiwiYmxvY2siOjgwNzgwMCwiYW5jaG9yX2Jsb2NrIjo4MDc4MDB9"
}
```

but when we do this call from our server the response looks so
```
{"data":[]}
```

So cursor is missing for some reason. 
How it could be and how to solve this?

**Comment by madninja** [comment]
@APshenkin the api responses are cached by Fastly. In the response you can see that the `x-cache` was a MISS meaning that Fastly actually asked the backend api for the data. 

I don't know why you were getting completely empty response there. Was that data in the same minute as the account being created? 

And does the problem still happen right now?

**Comment by APshenkin** [comment]
For now it's showing correct information about address. 

Account was created long time ago and we got this response for one day. Cache was cleared after some time and now we get correct information
