### ISSUE TITLE
large integers in JSON should be strings

### ISSUE THREAD

**Issue by allenan** [helium/blockchain-etl#163]
JS doesn't have a native way to handle large integers.

> Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers

for timestamps with ms precision such as in the `witness_info` object, the convention is to return them as strings and let the client decide how to turn those into big integers using a library such as biginteger.js for example.

**Comment by madninja** [comment]
Note that in the fix above this will only happen for newly inserted witnesses @allenan
