### ISSUE TITLE
Geocoder didn't populate properly the fields

### ISSUE THREAD

**Issue by rootvanished** [helium/blockchain-etl#184]
While asserting a new location the transaction (jCXd_kHqXg6BSAfXRwCWHol1l9Ctbw2rpMxv5xuyKns) was successful, the new coordinates were taken and the explorer diaplays the hotspot on the correct place. However the street details are all null and the hotspot is listed as "no location asserted" on the app, and "no location set" on web.

The describe hotspot API outcome is as follows:
{"short_street":null,"short_state":null,"short_country":null,"short_city":null,"long_street":null,"long_state":null,"long_country":null,"long_city":null,"city_id":null}

The hotspot address is: 11M5x6iGL1BTMzthT33kTc1u86hTaxhVmkimsTCREjHkATGqowy

The  hotspot name is: 
ITCHY MOCHA FINCH

Thank you

**Comment by cokes518** [comment]
seeing a few others in the community about this: https://discord.com/channels/404106811252408320/404106811252408322/850032148278804511

**Comment by madninja** [comment]
Ops gremlin. Unclear what the underlying issue was but a restart fixed it right away
