### ISSUE TITLE
issue connecting to S3 - Hotspot Sync Issue

### ISSUE THREAD

**Issue by Lucky7999** [helium/blockchain-etl#185]
Hi,

My hotspot not able to sync to block chain its been more than 24 hrs,
i contacted  Nebra team, they said this might be due to S3 issue, request you to please take a look at this

hotspot name: Chilly Sandstone Jay

**Comment by PharkMillups** [comment]
Hello. Nebra should be working to update your Hotspot. This repo isn't the place to report this issue. Closing. Thanks.
