### ISSUE TITLE
new endpoint to show hotspots that have witnessed you

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-etl#188]
satisfies https://github.com/helium/explorer/issues/144 and improves placement, understanding RF, overall usability.

**Comment by madninja** [comment]
This is satisfied by either the `/v1/hotspots/:address/witnesses` or `/v1/hotspots/:address/witnessed` enpoints. Please re-open if you meant something else?

**Comment by GP-Colorado** [comment]
It's been almost seven months since I posted #144. I forgot about it. I will re-read tonight.
Thanks, 
GP
