### ISSUE TITLE
Collecting of burns is not there in the etl for HTLC transcations

### ISSUE THREAD

**Issue by maco2035** [helium/blockchain-etl#194]
There is a miss-match in the etl, that doesn't record the HTLC transactions in the etl server. This may throw some issues, as there is no record on the etl where people quarry the accounts for the transactions there will be a miss-match in the amount sent and the burn for the transaction.

I will make a pull request and add this issue to the pull request.

**Comment by madninja** [comment]
I'm going to close this as not quite right.. the HTLC transactions are recorded as is the actual dc burn for that transaction. What is _not_ captured is any implicit burn that happens which is a separate feature that needs to be added
