### ISSUE TITLE
Add Support for SeenVectors

### ISSUE THREAD

**Issue by chrisabruce** [helium/blockchain-etl#208]
As a validator operator, I would like to be able to analyze seen penalties by looking at the actual votes from each validator in CG, so that I could better troubleshoot validator performance and perhaps identify any nefarious activity.

Since `SeenVectors` are a bitmap, anything that could be done to make this easy to query in ETL db would be greatly appreciated.

**Comment by madninja** [comment]
ugh.. how would you like to query it?
