### ISSUE TITLE
Online status shows up as null after xfer of validator

### ISSUE THREAD

**Issue by densone** [helium/blockchain-etl#212]
Someone transferred a validator to us today and everything seems to be fine but the API is reporting some NULL data even though heartbeat is working. Could this be bug when transferring a validator? 

`https://api.helium.io/v1/validators/112kc2g3kE2z9DCqFXQCFhPa8XTZJJe9s4Yd8kzTf5dcMYFPSsjp`

`"status":{"online":null,"listen_addrs":null,"height":null},`

**Comment by madninja** [comment]
First suspicion is just api gossip delay. Is it still like that?

**Comment by ytx1991** [comment]
It's almost 12 hours, still showing offline. This validator was transferred once, not sure if it does matter.

**Comment by madninja** [comment]
@ytx1991 @densone I changed the selection of rows to update to hopefully do better at getting to an update. Check now?
