### ISSUE TITLE
missing_block 0

### ISSUE THREAD

**Issue by FTwOoO** [helium/blockchain-etl#219]
what the hell when i check the etl status:
> $ docker exec -it  helium-blockchain-etl /bin/sh
> /opt/etl # blockchain_etl repair  sync_pause
> ok
> /opt/etl # blockchain_etl repair analyze
> error: {missing_block,0}

**Comment by madninja** [comment]
No need to swear.. 

If you're etl is syncing normally and info height is increasing you should have nothing to repair
