### ISSUE TITLE
Geocoding seems to fail to get a country code for Northern Cyprus

### ISSUE THREAD

**Issue by abhay** [helium/blockchain-etl#235]
More details in https://github.com/helium/miner/issues/1031.

https://api.helium.io/v1/hotspots/112CA7UxpkFPUM5QEbeAT5MqrH6Z7AEqDjKptV3H2LzBv29SCofF

**Comment by abhay** [comment]
Reverse geocoder response as the data but I the problem is described in this line:

https://github.com/helium/blockchain-etl/blob/master/src/be_db_geocoder.erl#L259

The first result does not include a country code. This would be a good issue to tackle if someone in the community wants to make a quick fix.

**Comment by licentia88** [comment]
this is my hotspot at norther Cyprus, 
https://explorer.helium.com/hotspots/112GBRdLxrGowtqKyxz9o9DffyQx21YXSxALf6dJrQ6ct8fdbkkN
I would appreciate if bobcat devs could manually assert location to my device.

**Comment by ccavusoglu0** [comment]
Anyone is working on this so far?

**Comment by caferelgin** [comment]
Is this commit deployed? Do we need to reassert location?

**Comment by madninja** [comment]
> Is this commit deployed? Do we need to reassert location?

It will be deployed today, and no you will not need to reassert location just restart your hotspot(s)
