### ISSUE TITLE
Issues while setting up blockchain-etl node

### ISSUE THREAD

**Issue by debasish22** [helium/blockchain-etl#236]
Hi Team,

I have followed the steps mentioned in the readme file and finally when i run sudo maker release command i get the below issue. OpenSSl is already installed .

My ubuntu version 20.4
OpenSSL version 1.1.1

Can any one help me with this issue

<img width="946" alt="heliumblockchain-issue" src="https://user-images.githubusercontent.com/30689502/133642431-77224afc-8397-4533-a47f-503e2f170226.PNG">

**Comment by nosmaster89** [comment]
I had this issue with 20.4 open SSL 1.1 is installed erlang depends on 1.0

**Comment by madninja** [comment]
this looks like you installed erlang 24 instead of erlang 23. ETL will not compile with erlang 24. Please install an erlang 23 version and pin it as a dependency to avoid accidentally upgrading to erlang 24
