### ISSUE TITLE
Hotspot hex re-asserted

### ISSUE THREAD

**Issue by Adrianek2000** [helium/blockchain-etl#252]
Hi guys,
Blurry Myrtle Dachshund here 
3 days ago, I have noticed that my hotspot location hex has moved without me changing the location 
If you see on the map, my location is at Arundel Square in Maidstone but I have been re-asserted to a different hex now!
Since then I moved from 1.0 reward scale to 0.83
Can someone help me please?🙏

Picture below shows where I am now and red dot shows where I was before system re-asserted my location
![image](https://user-images.githubusercontent.com/93798925/140586145-bb50a91b-30c9-406d-8848-e86c31d85177.jpeg)

**Comment by madninja** [comment]
This is unrelated to this repo and a question that has been asked and answered in Discord too. Please ask in the #explorer channel on Discord
