### ISSUE TITLE
Makefile: 42 - exec: cargo: not found

### ISSUE THREAD

**Issue by sawyerru** [helium/blockchain-etl#254]
When I run make release, the script says that cargo cannot be found. However, I have already installed rustup successfully with cargo and can see the program and version.

![image](https://user-images.githubusercontent.com/30737015/140772806-066d7368-d147-4787-aa50-3f58c37b4d8f.png)

Is there any issue with the versions of these? In some previous issues I saw people needed to be specific about versions.

**Comment by madninja** [comment]
You l likely installed rust, and failed to add it to you your path per the rustup instructions. Then open a new terminal so it picks up the updated rust paths and try again.

**Comment by sawyerru** [comment]
I've added cargo to PATH, and here's the PATH var: `/home/US/sawyer/.cargo/bin:<someother_bin>`. 

I set it manually and reset the terminal. This variable value is after the reset.

**Comment by madninja** [comment]
rustup install has instructions on how to install cargo properly. We'll close this for now.

**Comment by sawyerru** [comment]
@madninja I'm still facing issues related to my set up. It seems like the rustup/cargo install is the problematic component. I followed the default settings for installing rustup (location $HOME/cargo), but I have multiple users on the machine, so $HOME would be different for each. Would this be the setup error or how else should I go about diagnosing the issue? 

Thanks.
