### ISSUE TITLE
Privilege for placers according to placement date

### ISSUE THREAD

**Issue by jeanmouawad** [helium/blockchain-etl#258]
People who place first must have higher rewards than people who come and ruins the scale. Lower both people scales but give privileges for the one who placed at first.

**Comment by madninja** [comment]
This is not the place for proposing changes to the blockchain consensus rules. If you feel strongly about this, come into Discord into the `#helium-improvement-proposals`, get some consensus and propose a HIP for the community to address.

**Comment by jeanmouawad** [comment]
Ok thank you
