### ISSUE TITLE
How can I speed blockchain-etl up?

### ISSUE THREAD

**Issue by thomas-cloud579** [helium/blockchain-etl#267]
I built blockchain-etl and blockchain-http service, but the block information is too slow to enter the postgres database. This process is too slow and long, How can I speed it up?

**Comment by madninja** [comment]
Use a DeWi postgres database dump. Please check in Discord in the blockchain-development channel

**Comment by jamiew** [comment]
@thomas-cloud579 in case you're not on Discord: https://etl-snapshots.dewi.org/

**Comment by Degfy** [comment]
https://etl-snapshots.dewi.org/  "Internal Server Error"

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/15191087/161673987-e444410f-68c4-47be-8917-74e08d787bb3.png">
