### ISSUE TITLE
Make Docker images public

### ISSUE THREAD

**Issue by yagop** [helium/blockchain-etl#270]
Can you make published Docker images available, please?

You can push to `quay.io` as you do with `miner` so we can pull from there

**Comment by wolasss** [comment]
+1 Would be nice to have it on dockerhub/quay.io on each release

I am working on a kubernetes helm chart to run own private helium API and for now I have to build the images and send them to the remote cluster by hand which is a bit cumbersome

**Comment by disk91** [comment]
+1
