### ISSUE TITLE
Helium Explorer hotspot location off by more than 3 miles

### ISSUE THREAD

**Issue by TKingConsultant** [helium/blockchain-etl#273]
This map includes a google map overlay that shows the distance between the Helium Explorer location and the actual location of my hotspot..
![HeliumExplorer Issue](https://user-images.githubusercontent.com/95381551/144307786-442eee7a-1c11-450c-890a-9fa2d29ddddb.jpg)
.

**Comment by madninja** [comment]
Unrelated to blockchain-etl. Please join us on Discord in the #explorer channel to get help/explanations for what you are seeing
