### ISSUE TITLE
In the wrong hex

### ISSUE THREAD

**Issue by De-stress** [helium/blockchain-etl#282]
On the explorer map I am in the wrong hex…see attachment…I am the red dot.. when I go to change location in the app, it has me in correct location. What to do?![image](https://user-images.githubusercontent.com/96504933/147015741-c8785e39-46d4-46ea-8676-5b1facde68f4.jpeg)

**Comment by De-stress** [comment]
I would like to be in the HEX    That the actual address is in. Obviously that's a better hex and where my miner should be located! Any help here is most appreciated.

**Comment by jamiew** [comment]
This repository is for blockchain-etl not general support
