### ISSUE TITLE
Make JSON object types the same for keys that contain numbers

### ISSUE THREAD

**Issue by nhatfield** [helium/blockchain-etl#295]
Any chance in having the number types remain the same for a given value? Right now SNR can either be a float or long and it messes with some document stores...
example:
`snr: -7`
vs
`snr: -7.0`

**Comment by madninja** [comment]
> Any chance in having the number types remain the same for a given value? Right now SNR can either be a float or long and it messes with some document stores...
> example:
> `snr: -7`
> vs
> `snr: -7.0`

Are you asking this as a fix for the API vs ETL/SQL?

**Comment by nhatfield** [comment]
Ugh, sorry you're correct this should've been on the API instead I'll make a ticket there instead
