### ISSUE TITLE
True location is incorrect. 

### ISSUE THREAD

**Issue by CryptoProfitLink** [helium/blockchain-etl#303]
Hello, I have installed my machine! However the location is not accurate and it’s affecting my earnings. I have paid/submitted the location change form but nothing corrected. I have attached 2 pics. 1, is the broad view of explorer and the 2nd is a close up, which I circled my residence. Please review and correct as there are no other miners in my true hex. Thank you.

*I understand that they reflect in the middle of the hex however it is still the incorrect hex. 

BEST PLUM Llama
Address. 14mNLHYjVerdMZn3hGdXy2VAGj2ZycGbheUqrTyyvwHPnkxDwtD
![EF2C9D6C-A9AB-4AF7-BBDA-F488F17C00FB](https://user-images.githubusercontent.com/101420817/157916086-462fc7bc-7eaa-41fc-a89c-2969147e8a14.jpeg)
![78D77382-D929-40AE-BAEA-15B13354DDAF](https://user-images.githubusercontent.com/101420817/157916099-8cb55edd-5b01-434b-909b-9639d990f7f6.jpeg)

**Comment by madninja** [comment]
Please take this to the explorer channel on discord or move this issue to the explorer repo.
