### ISSUE TITLE
Hotspot misassignment

### ISSUE THREAD

**Issue by jagmclio** [helium/blockchain-etl#304]
Hello !!!

	Last Thursday 10, I install a sense cap with a 10 dBi antenna in Monteagudo, Murcia, Spain.

	I have an account with my 12 secret and 5 hotspot working on since a couple of month.

	When I try to sync up via Bluetooth with my helium official app wallet it gave me the following error:

	“There was an error construction the Add Hotspot transaction. Please try again later”. 

          I try it again 5 times and I couldn’t get it done. So I live it there until next day.

	The next day, I try to sync up with my helium app and I got this message:

	“This Hotspot already has an owner" 

         It loos like it was assigned or create automatically an account other than mine by mistake.

	This is the URL of the Hotspot: 
[	https://explorer.helium.com/hotspots/112rr8Y4eEyNbDzSz8rgqFfw1jVyAupS4jUMUUxBVoEhdukPFXrk](https://explorer.helium.com/hotspots/112rr8Y4eEyNbDzSz8rgqFfw1jVyAupS4jUMUUxBVoEhdukPFXrk)

	Please, let me know how can I fix this problem

	Thank you in advantage.

**Comment by madninja** [comment]
Sorry this is unrelated to the database or api that stores the blockchain information. Please join the community discord and ask in the #questions_and_answers channel
