### ISSUE TITLE
ETL snapshots site have error...

### ISSUE THREAD

**Issue by ynvv** [helium/blockchain-etl#309]
Whats wrong with etl snapshot site?
https://etl-snapshots.dewi.org

I cant download any snapshots. Every day have Internal Server Error

**Comment by madninja** [comment]
As you can tell from the domain name, DEWI snapshots are made by... DeWi.. please ask in Discord in the data-analysis or DeWi channels

**Comment by madninja** [comment]
> > The link is trying to be helpful
> 
> But download links doesnt work :)

they should start working again once DeWi gets their system working again.. Get on Discord and ask.

**Comment by dansku** [comment]
@ynvv this will be back working in a few days!
