### ISSUE TITLE
Helium Miner Location

### ISSUE THREAD

**Issue by beloslav177** [helium/blockchain-etl#321]
Hello,

Yesterday 23.2.2022 I updated my miner with the name: "Magnificent Caramel Poodle" from the address "Pražská 6, Bratislava 831 01" to "Pražská 27, Bratislava 831 01", I moved it from my residence, where I am renting, to my girlfriend's residence, for the reason to move from the hexagon, which has the color of orange, to the color of blue, which belongs to the address "Pražská 27, Bratislava 831 01". For some unknown reason, I have been assigned to the hexagon below this one with the colour red, and this is extremely inconvenient for me, as I should be assigned to the correct position. I will ask for an explanation and then adjust my location to the blue zone for Earnings, as this was the reason for the location change and I have already invested my fees in it.

![image](https://user-images.githubusercontent.com/58074163/164991707-dc458a8f-fb49-4ad3-a936-c8f4fd7164ee.png)

On Dark Blue Color is pointed my exactly location, can you please explain this kind of issue ? 

Thank you for your reply, I am available here in case you need authentication. Please see my miner history.

Thank you for your reply.

Lukas Belay

**Comment by madninja** [comment]
This is not the repo to file issues for explorer display. I notice you also raised this on discord. Closing this here. File it on the explorer repo if you did not get an answer on discord.
