### ISSUE TITLE
Incorrect hotspot location

### ISSUE THREAD

**Issue by bonifaaac** [helium/blockchain-etl#333]
Hello support teaam.

I have an issue. I have added a new hotspot yesterday but instead of location i actually register it, it registered on some island naer africa where i am definitely located. I dont want to pay relocation fee as it was first registering of the hotspot. Please check screenshot below and help me to relocate to correct location or reset the hotstop so i can add it again.

Thanks

Hotspot name - Chilly Sandstone Terrier

https://explorer.helium.com/hotspots/112FWhSBhYnaaDLc41CK3qpKeqUCHPfGrBT7CqpMkpDuix9BEmqb

height should be 10m I have bobcat 300 miner with stock 4dbi antenna

![image-20221705-110922 (1)](https://user-images.githubusercontent.com/105880097/169365203-767a2b71-14d5-4f82-838b-e4a6b71b2d27.jpeg)
![image-20221705-110922 (1)](https://user-images.githubusercontent.com/105880097/169365247-5be251a2-8c8a-45e0-b39b-3b3e86efb468.jpeg)

**Comment by madninja** [comment]
This is not the support team, or place for location/hotspot issues. Please ask in discord in the explorer channel or file an issue on the explorer repo
