### ISSUE TITLE
hexes problem

### ISSUE THREAD

**Issue by mpasha2020** [helium/blockchain-etl#350]
Hello dear helium support team i changed my hotspot location about 5 days ago but my hotspot hexagon didn’t  formed yet . My hotspot still have connection to internet
 My hotspot name - Magic Lava Weasel
https://explorer.helium.com/hotspots/112tpdq29Rg8DfzG2eREq2nAYie3kman8D9AxXt2ABEAifRvDmUe

**Comment by madninja** [comment]
This is not an ETL issue.. please report in the explorer repo or on discord
