### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mpasha2020** [helium/blockchain-etl#352]
Hello dear helium support team i changed my hotspot location about 6 days ago but my hotspot hexagon didn’t formed yet . My hotspot still have connection to internet
My hotspot name - Magic Lava Weasel
https://explorer.helium.com/hotspots/112tpdq29Rg8DfzG2eREq2nAYie3kman8D9AxXt2ABEAifRvDmUe

**Comment by madninja** [comment]
Again this is _NOT_ an ETL problem, but a potential report of an explorer bug. Please stop posting here.. last warning

**Comment by mpasha2020** [comment]
so what should i do who will help me
