### ISSUE TITLE
Asserted in wrong hex

### ISSUE THREAD

**Issue by BFBuffalo** [helium/blockchain-etl#355]
My hotspot Exotic Mahogany is asserted in the wrong hex making my scaling .28 versus .83.   Can this be corrected?
![EMS](https://user-images.githubusercontent.com/108416792/176469694-2330fd76-7715-4348-89de-f9c4048d2dc7.jpg)

**Comment by madninja** [comment]
Not an ETL issue. Either you need assert again in the right place or file a bug in explorer if you think the display is wrong
