### ISSUE TITLE
Docker image (last release) not starting

### ISSUE THREAD

**Issue by disk91** [helium/blockchain-etl#366]
```
Error relocating /opt/etl/erts-12.3.2.2/bin/beam.smp: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /opt/etl/erts-12.3.2.2/bin/beam.smp: pthread_getname_np: symbol not found
```

**Comment by madninja** [comment]
> Error relocating /opt/etl/erts-12.3.2.2/bin/beam.smp: _ZSt28__throw_bad_array_new_lengthv: symbol not found
> Error relocating /opt/etl/erts-12.3.2.2/bin/beam.smp: pthread_getname_np: symbol not found

Could you try the Dockerfile fixes proposed in https://github.com/helium/blockchain-etl/pull/367 please?

**Comment by DevSnap** [comment]
@madninja this worked for me, thanks!
