### ISSUE TITLE
Global Fetching API error

### ISSUE THREAD

**Issue by Palapilus** [helium/blockchain-etl#386]
Hello to all, well all hotspots have the isseu, can't fetch api (to add hotspot via bluetooth) , if you try to install a brand new hotspot with a brand new Wallet. Please help.

**Comment by madninja** [comment]
> Hello to all, well all hotspots have the isseu, can't fetch api (to add hotspot via bluetooth) , if you try to install a brand new hotspot with a brand new Wallet. Please help.

There was an helium api outage as well as a blockchain halt which may have caused this. Please retry
