### ISSUE TITLE
Error make relese: "Plugin rebar3_eqc does not export"

### ISSUE THREAD

**Issue by TommasoCere** [helium/blockchain-etl#387]
I have this problem when i run `make relese`

tom@VMslc:~/Documenti/blockchain-etl$ make release
curl -o priv/genesis.mainnet https://snapshots.helium.wtf/genesis.mainnet
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8870  100  8870    0     0  46660      0 --:--:-- --:--:-- --:--:-- 46931
curl -o priv/genesis.testnet https://snapshots.helium.wtf/genesis.testnet
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3310k  100 3310k    0     0  2980k      0  0:00:01  0:00:01 --:--:-- 2982k
curl -o priv/genesis.devnet https://snapshots.helium.wtf/genesis.devnet
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8982  100  8982    0     0  59185      0 --:--:-- --:--:-- --:--:-- 59483
./rebar3 as dev do release
===> Verifying dependencies...
===> Plugin rebar3_eqc does not export init/1. It will not be used.
sh: 1: exec: cc: not found
   Compiling proc-macro2 v1.0.32
   Compiling syn v1.0.81
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `syn` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` due to previous error
===> Hook for compile failed!

escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/home/runner/work/rebar3/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:42: release] Errore 127

**Comment by madninja** [comment]
Answered in Discord: Install developer tools, including a c compiler (clang). Please don't ask in multiple places.

**Comment by TommasoCere** [comment]
the problem is that I didn't have C compiler

**Comment by madninja** [comment]
> the problem is that I didn't have C compiler

Sure you do. On Ubuntu this is called build-tools and the list of dependencies to install is listed here: https://github.com/helium/blockchain-etl#installing-erlang-24-on-ubuntu

If you're also commenting in Discord please don't also comment here. It'd be easier for you to get help in the #etl-development channel on Discord
