### ISSUE TITLE
synchronization issue

### ISSUE THREAD

**Issue by athena0416** [helium/blockchain-etl#43]
HI 
I'm a developer of an exchange.
 I build the blockchain-etl and blockchain-http from source code in UBUNTU 18:04 . and it starts to synchronize about a day. The synchronization stuck and the error message is :

>@blockchain_gossip_handler:add_block:75 Something bad happened: {error,block_higher_than_assumed_valid_height}
>@blockchain_worker:start_sync:609 unknown starting <0.17893.8> #Ref<0.2792054433.1529610242.196230>

And I have changed port in sys.config, Is it effect the synchronization?
Thanks a lot, and waiting for your kind help.

**Comment by madninja** [comment]
@athena0416 that error is harmless, it's the blockchain saying that it saw a block that it's not ready to integrate yet. 

It would be good to see a more complete log output to see what the problem is that you're having.

**Comment by madninja** [comment]
While we debug this, I believe you can get it to move past this stall by stopping and starting the etl application

**Comment by athena0416** [comment]
Thanks, Madninja, it was settled.

**Comment by athena0416** [comment]
Hi Madninja, could you give me a blockchain explore address and an example of signing then
the broadcasting process to finish a transaction.

**Comment by athena0416** [comment]
When the synchronization to 200,000 height the sync speed is slow.  What's the reason for that. CPU network speed or SSD HHD speed? Thanks for your help, Madninja.

**Comment by madninja** [comment]
The blockchain goes faster up to an "assumed valid" block that is encoded in the configuration for etl. Once it gets to that known block it has to verify every block from then on which slows down block sync and storage. 

Usually we run etl on an 8 core machine to get verification done as quickly as possible.
