### ISSUE TITLE
Make Release Error - Makefile:41

### ISSUE THREAD

**Issue by pravino** [helium/blockchain-etl#90]
Get Following Error When Running make release

===> Compiling eql
===> Compiling goldrush
===> Compiling lager
===> Compiling relcast
===> Compiling throttle
===> Compiling ranch
_build/default/lib/ranch/src/ranch_ssl.erl:131: Warning: ssl:ssl_accept/2: deprecated; use ssl:handshake/2 instead

===> Compiling rand_compat
===> Compiling intercept
===> Compiling inet_cidr
===> Compiling inet_ext
===> Compiling nat
===> Compiling erl_base58
===> Compiling base32
===> Compiling multiaddr
===> Compiling enacl
===> Compiling /home/ubuntu/blockchain-etl/c_src/aead.c
===> /home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_KEYBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:14:31: error: âcrypto_aead_chacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_chacha20poly1305_ietf_KEYBYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c:14:31: note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_NPUBBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:20:31: error: âcrypto_aead_chacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_chacha20poly1305_ietf_NPUBBYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_ABYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:26:31: error: âcrypto_aead_chacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_chacha20poly1305_ietf_ABYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAXâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:33:26: error: âcrypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAXâ undeclared (first use in this function)
                          crypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAX);
                          ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_encryptâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:52:19: error: âcrypto_aead_chacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   if (key.size != crypto_aead_chacha20poly1305_ietf_KEYBYTES)
                   ^
/home/ubuntu/blockchain-etl/c_src/aead.c:54:21: error: âcrypto_aead_chacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   if (nonce.size != crypto_aead_chacha20poly1305_ietf_NPUBBYTES)
                     ^
/home/ubuntu/blockchain-etl/c_src/aead.c:58:30: error: âcrypto_aead_chacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
                              crypto_aead_chacha20poly1305_ietf_ABYTES,
                              ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_decryptâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:95:25: error: âcrypto_aead_chacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
   if (ciphertext.size < crypto_aead_chacha20poly1305_ietf_ABYTES)
                         ^
/home/ubuntu/blockchain-etl/c_src/aead.c:97:19: error: âcrypto_aead_chacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   if (key.size != crypto_aead_chacha20poly1305_ietf_KEYBYTES)
                   ^
/home/ubuntu/blockchain-etl/c_src/aead.c:99:21: error: âcrypto_aead_chacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   if (nonce.size != crypto_aead_chacha20poly1305_ietf_NPUBBYTES)
                     ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_KEYBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:131:31: error: âcrypto_aead_xchacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_xchacha20poly1305_ietf_KEYBYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_NPUBBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:137:31: error: âcrypto_aead_xchacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_xchacha20poly1305_ietf_NPUBBYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_ABYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:143:31: error: âcrypto_aead_xchacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
   return enif_make_int64(env, crypto_aead_xchacha20poly1305_ietf_ABYTES);
                               ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAXâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:150:26: error: âcrypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAXâ undeclared (first use in this function)
                          crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAX);
                          ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_encryptâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:170:19: error: âcrypto_aead_xchacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   if (key.size != crypto_aead_xchacha20poly1305_ietf_KEYBYTES)
                   ^
/home/ubuntu/blockchain-etl/c_src/aead.c:172:21: error: âcrypto_aead_xchacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   if (nonce.size != crypto_aead_xchacha20poly1305_ietf_NPUBBYTES)
                     ^
/home/ubuntu/blockchain-etl/c_src/aead.c:176:30: error: âcrypto_aead_xchacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
                              crypto_aead_xchacha20poly1305_ietf_ABYTES,
                              ^
/home/ubuntu/blockchain-etl/c_src/aead.c:181:3: warning: implicit declaration of function âcrypto_aead_xchacha20poly1305_ietf_encryptâ [-Wimplicit-function-declaration]
   crypto_aead_xchacha20poly1305_ietf_encrypt(
   ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_decryptâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:213:25: error: âcrypto_aead_xchacha20poly1305_ietf_ABYTESâ undeclared (first use in this function)
   if (ciphertext.size < crypto_aead_xchacha20poly1305_ietf_ABYTES)
                         ^
/home/ubuntu/blockchain-etl/c_src/aead.c:215:19: error: âcrypto_aead_xchacha20poly1305_ietf_KEYBYTESâ undeclared (first use in this function)
   if (key.size != crypto_aead_xchacha20poly1305_ietf_KEYBYTES)
                   ^
/home/ubuntu/blockchain-etl/c_src/aead.c:217:21: error: âcrypto_aead_xchacha20poly1305_ietf_NPUBBYTESâ undeclared (first use in this function)
   if (nonce.size != crypto_aead_xchacha20poly1305_ietf_NPUBBYTES)
                     ^
/home/ubuntu/blockchain-etl/c_src/aead.c:226:7: warning: implicit declaration of function âcrypto_aead_xchacha20poly1305_ietf_decryptâ [-Wimplicit-function-declaration]
   if (crypto_aead_xchacha20poly1305_ietf_decrypt(
       ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_KEYBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:15:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_NPUBBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:21:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_ABYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:27:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAXâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:34:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_KEYBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:132:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_NPUBBYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:138:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_ABYTESâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:144:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/ubuntu/blockchain-etl/c_src/aead.c: In function âenacl_crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAXâ:
/home/ubuntu/blockchain-etl/c_src/aead.c:151:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

Makefile:41: recipe for target 'release' failed
make: *** [release] Error 1

**Comment by madninja** [comment]
It looks like you didn't install `libsodium-dev` per the instructions at: https://github.com/helium/blockchain-etl#installing-ubuntu-required-packages

**Comment by pravino** [comment]
i have already installed the packages before compiling.

sudo apt-get install libsodium-de

Reading package lists... Done

Building dependency tree

Reading state information... Done

libsodium-dev is already the newest version (1.0.8-5).

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by madninja** [comment]
@pravino What version of ubuntu are you on? You should have at least libsodium-dev 1.0.16 or higher installed
